# Generated by Django 4.0.6 on 2022-08-17 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='brand')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'BrandModel',
                'verbose_name_plural': 'BrandModels',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'CategoryModel',
                'verbose_name_plural': 'CategoryModels',
            },
        ),
        migrations.CreateModel(
            name='ProductTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'ProductTagModel',
                'verbose_name_plural': 'ProductTagModels',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('image', models.ImageField(upload_to='product', verbose_name='image')),
                ('price', models.FloatField()),
                ('short_description', models.TextField(default=0, verbose_name='short_discription')),
                ('short_description_en', models.TextField(default=0, null=True, verbose_name='short_discription')),
                ('short_description_ru', models.TextField(default=0, null=True, verbose_name='short_discription')),
                ('short_description_uz', models.TextField(default=0, null=True, verbose_name='short_discription')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brandmodul', verbose_name='brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category')),
                ('category_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category')),
                ('category_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category')),
                ('category_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags')),
                ('tags_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags')),
                ('tags_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags')),
                ('tags_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'ProductModel',
                'verbose_name_plural': 'ProductModels',
            },
        ),
    ]
