# Generated by Django 4.0.6 on 2022-08-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(default=5, max_length=250, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandmodul',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='brandmodul',
            name='title',
            field=models.CharField(max_length=250, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brandmodul', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(upload_to='product', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='short_discription',
            field=models.TextField(default=0, verbose_name='short_discription'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='producttagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='producttagmodel',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
    ]
