# Generated by Django 4.0.6 on 2022-08-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productmodel_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='category_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.categorymodel', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tags_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tags_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='tags_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.producttagmodel', verbose_name='tags'),
        ),
    ]
