# Generated by Django 4.0.6 on 2022-08-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='post')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AuthorModel',
                'verbose_name_plural': 'AuthorModels',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'TagModel',
                'verbose_name_plural': 'TagModels',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('title_en', models.CharField(max_length=250, null=True)),
                ('title_ru', models.CharField(max_length=250, null=True)),
                ('title_uz', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(upload_to='post')),
                ('banner', models.ImageField(upload_to='banner')),
                ('banner_en', models.ImageField(null=True, upload_to='banner')),
                ('banner_ru', models.ImageField(null=True, upload_to='banner')),
                ('banner_uz', models.ImageField(null=True, upload_to='banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.authormodel')),
                ('author_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.authormodel')),
                ('author_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.authormodel')),
                ('author_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.authormodel')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.tagmodel')),
                ('tags_en', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.tagmodel')),
                ('tags_ru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.tagmodel')),
                ('tags_uz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='post.tagmodel')),
            ],
            options={
                'verbose_name': 'PostModel',
                'verbose_name_plural': 'PostModels',
            },
        ),
    ]
