# Generated by Django 4.0.6 on 2022-08-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'ContactModel', 'verbose_name_plural': 'ContactModels'},
        ),
    ]
